INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (372, 'Kkingo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (383, 'Madu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (215, 'Entebbe Division B');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (305, 'Sironko Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (386, 'Olio');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (500, 'Makulubita');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (79, 'Kyazanga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (76, 'Kyanamukaaka');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (341, 'Omodoi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (514, 'Bukomero s/c');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (48, 'Aromo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (564, 'Mpunge');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (246, 'Najjembe');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (224, 'Nabweru');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (253, 'Butaleja');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (471, 'Buseta');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (632, 'Bukhadala');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (241, 'Njeru Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (186, 'Busedde');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (284, 'Layibi Division');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (18, 'Mukono Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (415, 'Kirewa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (143, 'Kiringente');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (221, 'Masulita');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (57, 'Busoba');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (527, 'Nalweyo-kisita');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (232, 'Kira');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (38, 'Amach');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (591, 'Buyanga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (314, 'Lyantondee');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (463, 'Kaderuna');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (230, 'Wakiso Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (25, 'Kyampisi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (516, 'Kapeke S/C');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (643, 'Kyebando');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (617, 'Hakabaale');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (436, 'Nakasongola Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (338, 'Usuk');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (345, 'Nairambi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (51, 'Namanyonyi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (176, 'Kwera');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (708, 'Palorinya');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (712, 'Kitumbi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (825, 'Kaliro Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (687, 'Nyakashashara');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (722, 'Midigo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (70, 'Bukakata');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (630, 'Bukusu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (250, 'Budumba');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (151, 'Aduku');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (33, 'Adyel Division');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (217, 'Kakiri');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (809, 'Mayuge Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (67, 'Kingo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (552, 'Bukuya');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (549, 'Nabingoola');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (172, 'Agwata');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (736, 'Ariva');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (477, 'Kabwangasi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (369, 'Kalungo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (111, 'Kibanda');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (145, 'Maddu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (473, 'Tirinyi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (468, 'Kibuku');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (499, 'Wobulenzi Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (616, 'Kabarole Eastern');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (401, 'Ngoraa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (392, 'Bulago');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (126, 'Makindye East');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (690, 'Parabongo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (330, 'Kanyum');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (775, 'Padibe');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (501, 'Nyimbwa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (259, 'Bududa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (206, 'Kamuda');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (260, 'Bududa Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (209, 'Soroti Municipal Northern');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (648, 'Kakumiro tc');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (184, 'Wabwoko - Kitimbwa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (654, 'Buhanika');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (440, 'Kaberimaido');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (558, 'Koch Goma');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (439, 'Alwa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (470, 'Bulangira');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (11, 'Maanyi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (533, 'Masafu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (541, 'Mubende Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (334, 'Nyero');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (40, 'Lira');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (97, 'Rakai Town');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (146, 'Mpenja');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (713, 'Odravu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (229, 'Ssisa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (553, 'Hapuuyo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (414, 'Paya');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (3, 'Nakaseke');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (426, 'Rubongi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (745, 'Bileafe');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (540, 'Madudu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (695, 'Byelima');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (205, 'Gweri');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (506, 'Kikyusa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (698, 'Bukuya');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (624, 'Rwiimi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (165, 'Loro');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (723, 'Ukusijohn');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (125, 'City Centre');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (582, 'Mofutu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (228, 'Nsangi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (271, 'Butiru');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (381, 'Kabulasoka');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (286, 'Ongako');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (444, 'Anyara');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (170, 'Iceme');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (351, 'Abakoo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (550, 'Kibalinga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (368, 'Kyamuliba');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (167, 'Minakulu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (180, 'Busana');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (324, 'Orungo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (686, 'Bukedea Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (578, 'Nabbogo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (62, 'Nakaloke');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (194, 'Buwenga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (342, 'Ngariam');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (105, 'Kacheera');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (720, 'Lodonga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (498, 'Katikamu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (522, 'Igayaza Parish');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (327, 'Bukedea Sub County');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (164, 'Ibuje');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (129, 'Kampala Central');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (467, 'Kameruka');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (382, 'Kyegonzaa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (387, 'Katete');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (322, 'Kuju');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (431, 'Kalongo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (530, 'Buhehe');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (673, 'Malaba Town');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (537, 'Busia T/C');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (261, 'Bukibokolo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (214, 'Entebbe Division A');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (437, 'Nakitoma');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (756, 'Arua Hill');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (606, 'Ibanda TC');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (336, 'Magoro');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (735, 'Ajia');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (714, 'Kei');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (236, 'Mateete');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (281, 'Lakwana');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (682, 'Kyankwanzi tc');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (110, 'Kasasa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (523, 'Kabanyoro');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (725, 'Pakele');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (21, 'Kasawo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (266, 'Bubutu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (526, 'Kiryanga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (779, 'Lokole');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (821, 'Wairasa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (350, 'Aloii');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (133, 'Mpigi Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (247, 'Buikwe');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (83, 'Nyendo-Ssenyange Division');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (443, 'Kaberimaido Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (55, 'Busano');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (513, 'Muwanga s/c');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (664, 'Kiziranfumbi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (551, 'Kiyuni');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (182, 'Kayonza');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (466, 'Naboa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (59, 'Wanale Borough Div.');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (208, 'Soroti Municipal Eastern');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (200, 'Atiira');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (739, 'Nvara');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (74, 'Katwe-Butego Division');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (123, 'Rakai Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (277, 'Bar-dege Division');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (109, 'Kasaali');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (139, 'Buwama');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (173, 'Dokolo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (234, 'Lwebitakuli');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (213, 'Tubur');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (1, 'Kasangombe');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (319, 'Morungatuny');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (255, 'Kachonga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (7, 'Semuto');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (256, 'Mazimasa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (679, 'Wattuba');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (397, 'Bukalu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (5, 'Kikamulo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (547, 'Bagezza');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (495, 'Butuntumula');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (702, 'Moyo Town');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (178, 'Kayunga Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (770, 'Palabek Gem');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (231, 'Wakiso');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (108, 'Kalisizo Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (204, 'Asuret');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (748, 'Yumbe Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (675, 'Kigando');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (294, 'Bukhulo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (371, 'Molongo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (771, 'Paluda');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (412, 'Molo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (98, 'Kyotera Adp');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (192, 'Budondo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (703, 'Laropi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (505, 'Zirobwe');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (509, 'Gayaza S/C');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (77, 'Kimanya-Kyabakuza Divisio');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (138, 'Bulo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (32, 'Ntunda');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (661, 'Busisi division');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (289, 'Patiko');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (168, 'Ngai');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (543, 'Kasambya');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (613, 'Buheesi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (348, 'Omoro');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (759, 'Manibe');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (847, 'Luuka Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (757, 'Pajulu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (147, 'Muduma');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (315, 'Amuria Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (104, 'Kabira');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (340, 'Kapujan');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (362, 'Kitandaa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (155, 'Akalo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (521, 'Birembo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (374, 'Lwengoo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (515, 'Kiboga T/C');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (567, 'Aligoi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (300, 'Butandiga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (812, 'Buwaaya');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (175, 'Batta');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (705, 'Lefori');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (101, 'Kagamba (Buyamba)');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (798, 'Central Division');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (323, 'Kapelebyong');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (646, 'Kabamba');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (117, 'Lwamagwa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (226, 'Nangabo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (508, 'Mulagi S/C');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (857, 'Nawampiti');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (850, 'Waibuga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (740, 'Logera');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (637, 'Kisiita');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (337, 'Katakwi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (233, 'Lugusulu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (317, 'Wera');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (52, 'Industrial Borough Div.');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (701, 'Moyo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (651, 'Kabwooya');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (799, 'Northern Division');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (419, 'Mulanda');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (642, 'Mabale');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (102, 'Byakabanda');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (447, 'Otuboi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (512, 'Dwaniro s/c');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (352, 'Bala');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (403, 'Makura');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (106, 'Kakuuto');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (435, 'Nabiswera');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (290, 'Pece Division');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (339, 'Ongongoja');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (562, 'Mpatta');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (634, 'Bubombi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (82, 'Ndagwe');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (2, 'Wakyato');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (628, 'Khabutoola');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (263, 'Bulucheke');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (390, 'Kadungulo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (709, 'Itula');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (554, 'Acet');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (41, 'Ogur');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (37, 'Barr');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (304, 'Muyembe');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (166, 'Aber');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (639, 'Kikwaya');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (806, 'Nawanyingi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (283, 'Laroo Division');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (391, 'Bugondu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (282, 'Lalogi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (309, 'Kaliro');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (239, 'Sembabule Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (264, 'Bumayoka');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (597, 'Nyabbani');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (134, 'Kamengo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (768, 'Palabek Ogili');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (406, 'OMalera');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (592, 'Bwiizi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (589, 'Magola');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (385, 'Kyeree');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (148, 'Ngando');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (546, 'Kiganda');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (732, 'Pakele town council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (249, 'Ngogwe');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (29, 'Nabbale');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (417, 'Iyolwa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (114, 'Kyalulangira');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (427, 'Tororo Municipality Weste');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (12, 'Malangala');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (808, 'Nabitende');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (561, 'Atyak');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (302, 'Buwalasi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (278, 'Bobi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (794, 'Alongo Town council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (128, 'Makindye West');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (373, 'Kyazangaa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (726, 'Ciforo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (507, 'Kamira');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (68, 'Buwunga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (80, 'Lwengo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (30, 'Nagojje');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (363, 'Bigasaa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (707, 'Mt Otce');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (119, 'Lwankoni');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (422, 'Mukujju');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (404, 'Ngora Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (729, 'Adjumani Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (292, 'Buhugu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (496, 'Luwero');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (378, 'Kalambaa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (399, 'Bunambutya');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (318, 'Asamuk');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (149, 'Mpigi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (413, 'Merikit');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (510, 'Kibiga s/c');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (607, 'Ishongororo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (320, 'Acowa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (656, 'Kyabigambire');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (638, 'Katikara');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (254, 'Butaleja Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (734, 'Vura');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (210, 'Soroti Municipal Western');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (356, 'Alitu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (157, 'Apac');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (588, 'Sopsop');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (39, 'Adekokwok');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (560, 'Paboo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (220, 'Kira Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (717, 'Drajini');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (428, 'Tororo Municipality Easte');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (650, 'Kigorobya');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (559, 'Lamogi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (738, 'Ajiya');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (532, 'Lumino');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (461, 'Budaka Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (75, 'Kabonera');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (100, 'Kalisizo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (623, 'Ruteete');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (814, 'Baitambogwe');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (20, 'Nakisunga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (834, 'Budomelo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (243, 'Wakisi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (163, 'Chawente');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (525, 'Kasambya');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (225, 'Namayumba');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (313, 'Lyantonde T.C');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (595, 'Mahyoro');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (235, 'Lwemiyaga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (16, 'Mityana Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (376, 'Bude');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (66, 'Kitanda');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (410, 'Kidongole');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (15, 'Busimbi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (17, 'Ssekanyonyi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (400, 'Muyemba');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (418, 'Nagongera');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (545, 'Kitenga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (132, 'Lubaga South');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (538, 'Dabani');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (469, 'Kibuku Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (511, 'Lwamata s/c');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (683, 'Ntwetwe');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (379, 'Kibibii');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (652, 'Buseruka');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (10, 'Butayunja');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (34, 'Ojwina Division');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (275, 'Sibanga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (131, 'Lubaga North');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (555, 'Anaka');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (188, 'Mafubira');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (116, 'Kyotera Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (647, 'Nkooko');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (803, 'Bulamagi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (279, 'Bungatira');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (13, 'Bulera');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (162, 'Apac Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (423, 'Kwapa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (333, 'Kumi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (251, 'Busaba');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (430, 'Kakooge');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (150, 'Nambieso');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (135, 'Nkozi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (140, 'Kabulasoke');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (464, 'Kamonkoli');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (685, 'Kumi sub county');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (716, 'Ariwa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (329, 'Ongino');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (678, 'Mulagi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (9, 'Kakindu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (503, 'Kalagala');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (152, 'Inomo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (800, 'Nakalama');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (190, 'Mpumudde/Kimaka');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (280, 'Koro');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (219, 'Katabi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (311, 'Kinuuka');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (63, 'Bungokho - Mutoto');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (438, 'Wabinyonyi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (113, 'Kirumba');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (776, 'Lukung');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (65, 'Kibinge');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (244, 'Kawolo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (801, 'Nakigo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (611, 'Nyamarebe');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (203, 'Arapai');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (212, 'Katine');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (557, 'Bisheshe');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (285, 'Odek');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (476, 'Butebo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (563, 'Unyama');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (626, 'Kabarole Western');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (689, 'Lokole');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (61, 'Nambale');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (715, 'Kululu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (706, 'Metu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (331, 'Mukongoro');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (365, 'Lukaya Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (659, 'Bugambe');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (676, 'Kasule');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (649, 'Kisengwe');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (118, 'Lwanda');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (316, 'Abarilela');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (216, 'Gombe');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (710, 'Aliba');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (534, 'Bulumbi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (727, 'Adropi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (425, 'Osukuru');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (222, 'Busukuma');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (36, 'Lira Central Division');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (158, 'Cegere');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (807, 'Namungalwe');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (169, 'Acaba');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (389, 'Pingira');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (50, 'Bukyiende');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (420, 'Kisoko');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (112, 'Kifamba');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (636, 'Kitaihuka');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (657, 'Buhimba');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (688, 'Patongo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (737, 'Pajara');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (325, 'Kumi Municipality');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (502, 'Bombo Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (4, 'Kapeeka');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (367, 'Lwabenge');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (421, 'Petta');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (14, 'Kikandwa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (741, 'Logiri');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (409, 'Kachumbala');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (35, 'Railways Division');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (237, 'Mijwala');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (174, 'Kangai');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (380, 'Ngandoo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (432, 'Kalungi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (207, 'Soroti');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (593, 'Nkoma');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (424, 'Mella');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (153, 'Abongomola');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (460, 'Budaka');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (728, 'Pacara');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (183, 'Kayunga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (517, 'Ntwetwe S/C');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (663, 'Bujumbura division');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (103, 'Ddwaniro');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (782, 'Parabongo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (829, 'Gadumire');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (177, 'Kangulumira');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (355, 'Abokee');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (696, 'Kitabona');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (73, 'Butenga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (539, 'Masaba');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (411, 'Kolir');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (127, 'Kawempe South');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (416, 'Nabuyoga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (137, 'Budde');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (122, 'Nabigasa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (377, 'Bolo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (130, 'Nakawa Division');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (536, 'Lunyo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (497, 'Luwero Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (408, 'Bukedea');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (272, 'Buwabwala');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (577, 'Buwanyanga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (711, 'Gimara');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (853, 'Bukanga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (548, 'Butoloogo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (124, 'Kawempe North');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (240, 'Ssi-Bukunja');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (191, 'Masese/Walukuba');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (721, 'Keriwa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (370, 'Kiseka');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (528, 'Mazuba');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (754, 'Adumi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (718, 'Kochi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (677, 'Butemba');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (719, 'Komogi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (58, 'Northern Borough Div.');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (531, 'Busitema');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (308, 'Buyaga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (384, 'Mpenjaa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (185, 'Nazigo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (72, 'Kalungu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (64, 'Mukungwe');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (23, 'Goma');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (366, 'Bukulula');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (662, 'Mparo division');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (312, 'Kasagama');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (542, 'Kasanda');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (402, 'Kapiri');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (518, 'Kahunge');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (136, 'Kituntu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (31, 'Seeta - Namuganga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (24, 'Nama');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (307, 'Mpumudde');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (429, 'Kiryandongo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (227, 'Nansana Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (22, 'Kimenyedde');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (535, 'Buteba');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (49, 'Bungokho');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (635, 'Bukiaba');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (287, 'Paicho');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (223, 'Ssabagabo - Makindye');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (446, 'Kalaki');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (364, 'Butengaa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (504, 'Bamunanika');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (680, 'Gayaza');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (267, 'Bugobero');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (519, 'Busiriba');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (758, 'Dadamu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (644, 'Pachwa');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (674, 'Lyakajura');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (816, 'Bugadde');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (640, 'Kijanji');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (767, 'Palabek Nyimur');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (99, 'Kooki Adp');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (769, 'Palabek Kal');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (407, 'Bukedea Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (121, 'Lyantonde Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (268, 'Bumbo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (462, 'Iki - Iki');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (660, 'Kahoora division');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (245, 'Lugazi Town Council');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (361, 'Kiibinge');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (353, 'Akallo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (47, 'Apala');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (218, 'Kasanje');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (388, 'Atira');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (19, 'Ntenjeru');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (684, 'Atutur');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (699, 'Makokoto');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (354, 'Ayeri');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (851, 'Bulanga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (596, 'Ntara');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (524, 'Kakindo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (349, 'Amugo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (742, 'Omugo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (520, 'Bugangaizi West');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (335, 'Toroma');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (56, 'Busiu');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (276, 'Awach');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (772, 'Lamwo');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (375, 'Ndagwee');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (615, 'Busoro');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (730, 'Dzaipi');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (625, 'Kabarole Southern');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (579, 'Buyaga');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (704, 'Dufile');
INSERT INTO sub__counties (subcounty_id, subcounty_name) VALUES (474, 'Kagumu');
